# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: 3

dotenv:
  - .env

tasks:
  setup:cilium:
    cmds:
      - helm repo add cilium https://helm.cilium.io/
      - helm repo update
      - |
        helm upgrade --install cilium cilium/cilium \
          --namespace kube-system \
          -f bootstrap/cilium/values.yaml \
          --wait

  setup:tailscale:
    cmds:
      - helm repo add tailscale https://pkgs.tailscale.com/helmcharts
      - helm repo update
      - |
        helm upgrade --install tailscale-operator tailscale/tailscale-operator \
          --namespace=tailscale \
          --create-namespace \
          --set-string oauth.clientId=$TAILSCALE_CLIENT_ID \
          --set-string oauth.clientSecret=$TAILSCALE_CLIENT_SECRET \
          --wait

  setup:argocd:
    cmds:
      - helm repo add argo https://argoproj.github.io/argo-helm
      - helm repo update
      - |
        helm upgrade --install argocd argo/argo-cd \
          --namespace argocd \
          --create-namespace \
          -f bootstrap/argocd/values.yaml \
          --wait
      - kubectl apply -f bootstrap/argocd/root-app.yaml

  secret:cnpg:
    vars:
      PG_PASSWORD:
        sh: openssl rand -base64 24
    cmds:
      - kubectl create namespace database --dry-run=client -o yaml | kubectl apply -f -
      - echo Generated password {{.PG_PASSWORD}}
      - |
        kubectl create secret generic cnpg-superuser-secret \
          --namespace database \
          --from-literal=username=postgres \
          --from-literal=password="{{.PG_PASSWORD}}" \
          --dry-run=client -o yaml | kubectl apply -f -
